version: "3"
services:
  main-app:
    build: .
    ports:
      - "3000:3000"
      - "4200:4200"
    volumes:
      - ./:/app
      - public-data:/app/public
      # prevents from overwritting node_modules
      - /app/node_modules
      - /app/client/node_modules
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage_2_catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  public-data: